#!/bin/bash

# DB_PATH=./KoboReader.sqlite
DB_PATH=/run/media/jayemar/KOBOeReader/.kobo/KoboReader.sqlite

if [ ! -e $DB_PATH ]; then
    echo -e "db unavailable at $DB_PATH\n=> Is kobo mounted?"
    exit 1
fi


# 0 arguments, list all books
if [ $# -eq 0 ]; then
    python3 ./export-kobo.py $DB_PATH --list

# 1 argument, export book number as markdown
elif [ $# -eq 1 ]; then
    python3 ./export-kobo.py $DB_PATH --bookid $1 --markdown


# 2 arguments, export book number to automatically named: USE THIS ONE!!
elif [ $# -eq 2 ]; then
    python3 ./export-kobo.py $DB_PATH --bookid "$1" --markdown --output -
    echo "Output written to '$(ls -t | head -n 1)'"


# more than 2 arguments are not allowed
else
    echo "More than two arguments were passed."
    # Handle cases with more than 2 arguments
fi
